import type { Request } from 'express'
import getUserData from './userData';

export default async function main(req: Request, permission: bigint): Promise<boolean> {
    const auth = req.headers.authorization as string; // Handler will make sure this exists before calling this function
    if (auth.startsWith('Guild ')) return true; // Guild keys are ultimately trusted as they can only be generated by the guild owner

    const userData = await getUserData({
        accessToken: auth.split(' ')[1]
    });
    if (!userData) return false;

    const guildData = userData.guilds.find((g) => g.id === req.query.guild);
    if (!guildData) return false;

    if (BigInt(guildData.permissions) & BigInt(8)) return true; // Administrator permission is basically a free pass
    if (BigInt(guildData.permissions) & permission) return false;
    return true;
}