name: Generation
run-name: ${{ github.actor }}
on:
  push:
    branches:
      '*'
    paths-ignore:
      - 'test.yml'
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
            node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Generate the documentation
        run: npm run generate:docs

      - name: Update resources
        uses: test-room-7/action-update-file@v1
        with:
          file-path: docs.json
          commit-msg: '[skip ci] [action] Update docs.json'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          branch: ts-rewrite