name: update
run-name: ${{ github.actor }}
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'test.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    needs: test
    steps:
    - name: Update files
      run: |
        echo "Updating files..."
        curl -X POST "https://api.daalbot.xyz/post/api/update?auth=${{ secrets.API_KEY }}"
    - name: Restart api
      run: |
        echo "Restarting api..."
        curl -X POST "https://api.daalbot.xyz/post/api/restart?auth=${{ secrets.API_KEY }}"

  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
            node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test