name: update
run-name: ${{ github.actor }}
on:
  push:
    branches:
      - master

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
    - name: Update files
      run: |
        curl -X POST "https://api.daalbot.xyz/post/api/update?auth=${{ secrets.API_KEY }}"
    - name: Restart api
      run: |
        curl -X POST "https://api.daalbot.xyz/post/api/restart?auth=${{ secrets.API_KEY }}"